package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"github.com/aiit2022-pbl-okuhara/play-security/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Mypage)
// DB Table: Plural (mypages)
// Resource: Plural (Mypages)
// Path: Plural (/mypages)
// View Template Folder: Plural (/templates/mypages/)

// MypagesResource is the resource for the Mypage model
type MypagesResource struct {
	buffalo.Resource
}

// List gets all Mypages. This function is mapped to the path
// GET /mypages
func (v MypagesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	mypages := &models.Mypages{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Mypages from the DB
	if err := q.All(mypages); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("mypages", mypages)
		return c.Render(http.StatusOK, r.HTML("mypages/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(mypages))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(mypages))
	}).Respond(c)
}

// Show gets the data for one Mypage. This function is mapped to
// the path GET /mypages/{mypage_id}
func (v MypagesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Mypage
	mypage := &models.Mypage{}

	// To find the Mypage the parameter mypage_id is used.
	if err := tx.Find(mypage, c.Param("mypage_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("mypage", mypage)

		return c.Render(http.StatusOK, r.HTML("mypages/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(mypage))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(mypage))
	}).Respond(c)
}

// New renders the form for creating a new Mypage.
// This function is mapped to the path GET /mypages/new
func (v MypagesResource) New(c buffalo.Context) error {
	c.Set("mypage", &models.Mypage{})

	return c.Render(http.StatusOK, r.HTML("mypages/new.plush.html"))
}

// Create adds a Mypage to the DB. This function is mapped to the
// path POST /mypages
func (v MypagesResource) Create(c buffalo.Context) error {
	// Allocate an empty Mypage
	mypage := &models.Mypage{}

	// Bind mypage to the html form elements
	if err := c.Bind(mypage); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(mypage)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("mypage", mypage)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("mypages/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "mypage.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/mypages/%v", mypage.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(mypage))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(mypage))
	}).Respond(c)
}

// Edit renders a edit form for a Mypage. This function is
// mapped to the path GET /mypages/{mypage_id}/edit
func (v MypagesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Mypage
	mypage := &models.Mypage{}

	if err := tx.Find(mypage, c.Param("mypage_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("mypage", mypage)
	return c.Render(http.StatusOK, r.HTML("mypages/edit.plush.html"))
}

// Update changes a Mypage in the DB. This function is mapped to
// the path PUT /mypages/{mypage_id}
func (v MypagesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Mypage
	mypage := &models.Mypage{}

	if err := tx.Find(mypage, c.Param("mypage_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Mypage to the html form elements
	if err := c.Bind(mypage); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(mypage)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("mypage", mypage)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("mypages/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "mypage.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/mypages/%v", mypage.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(mypage))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(mypage))
	}).Respond(c)
}

// Destroy deletes a Mypage from the DB. This function is mapped
// to the path DELETE /mypages/{mypage_id}
func (v MypagesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Mypage
	mypage := &models.Mypage{}

	// To find the Mypage the parameter mypage_id is used.
	if err := tx.Find(mypage, c.Param("mypage_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(mypage); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "mypage.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/mypages")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(mypage))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(mypage))
	}).Respond(c)
}
